version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "no changelog entry needed"
      - "dependencies"
      - "github_actions"
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: "daily"
    labels:
      - "no changelog entry needed"
      - "dependencies"
      - "javascript"
