plugins:
  eslint:
    enabled: true
    channel: "eslint-5"
    config:
      extensions:
        - .js
        - .ts
  fixme:
    enabled: true
  git-legal:
    enabled: true
exclude_patterns:
  - "**/*.spec.ts"
