# CircleCI configuration
# see: https://circleci.com/docs/2.0/configuration-reference/

version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
commands:
  run-all:
    steps:
      - checkout
      - restore_cache:
          name: Restore npm package cache
          key: v1-dependency-cache-nodejs-{{ checksum "./package.json" }}
      - run:
          name: Install dependencies
          command: npm i
      - save_cache:
          name: Save npm package cache
          key: v1-dependency-cache-nodejs-{{ checksum "./package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run linters
          command: npm run lint -- --max-warnings=0
      - run:
          name: Assemble typescript
          command: npm run build
      - run:
          name: Generate typedoc
          command: npm run docs
      - run:
          name: Run tests with junit reporter
          command: npm run test -- --reporter mocha-junit-reporter
          environment:
            MOCHA_FILE: ./mocha-report/test-results.xml
      - run:
          name: Run tests with mochawesome reporter
          command: npm run test
      - store_test_results:
          name: Store mocha test report
          path: ./mocha-report
      - codecov/upload:
          file: ./coverage/coverage-final.json
      - store_artifacts:
          name: Store coverage report as artifact
          path: ./coverage
      - store_artifacts:
          name: Store mochawesome HTML report
          path: ./mochawesome-report
      - store_artifacts:
          name: Store typedoc documentation
          path: ./docs
jobs:
  build-nodejs-12:
    docker:
      - image: circleci/node:12
    steps:
      - run-all
  build-nodejs-10:
    docker:
      - image: circleci/node:10
    steps:
      - run-all
  deploy-docs:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          name: Restore npm package cache
          key: v1-dependency-cache-nodejs-{{ checksum "./package.json" }}
      - run:
          name: Install dependencies
          command: npm i
      - save_cache:
          name: Save npm package cache
          key: v1-dependency-cache-nodejs-{{ checksum "./package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Generate typedoc
          command: npm run docs
      - run: git log -1 --pretty=format:'%B' | tee ../commit-msg
      - run: git log -1 --pretty=format:'%an <%ae>' | tee ../commit-author
      - run: git log -1 --pretty=format:'%at' | tee ../commit-time
      - run: cp -r ./docs/. ../docs/
      - run: mkdir ../docs/.circleci
      - run: cp ./.circleci/noop.yml ../docs/.circleci/config.yml
      - run: git checkout gh-pages || git checkout --orphan gh-pages
      - run: find -not -path "./.git/*" -not -name ".git" -delete
      - run: cp -r ../docs/. .
      - run: git add --all
      - run: >-
          GIT_AUTHOR_DATE="$(cat ../commit-time)"
          GIT_COMMITTER_NAME="Docs deployment bot"
          GIT_COMMITTER_EMAIL="noreply@robotty.de"
          git commit
          --allow-empty
          -m "$(cat ../commit-msg)"
          --author="$(cat ../commit-author)"
      - run: git push -u origin gh-pages

workflows:
  version: 2
  build-all:
    jobs:
      - build-nodejs-12
      - build-nodejs-10
      - deploy-docs:
          filters:
            branches:
              only:
                - master
